### ISSUE TITLE
Demo website is not parsing example METAR

### ISSUE THREAD

**Issue by JohnieWalker** [SagemCassiopee/php-metar-decoder#10]
Hi,

It appears that demo website is not parsing example METAR from the README fully. Is it as expected? 

METAR - "METAR LFPO 231027Z AUTO 24004G09MPS 2500 1000NW R32/0400 R08C/0004D +FZRA VCSN //FEW015 17/10 Q1009 REFZRA WS R03"

Error:

Invalid format:
* Bad format for clouds information, on chunk "//FEW015 17/10 Q1009 REFZRA WS R03"
* Atmospheric pressure not found, on chunk "//FEW015 17/10 Q1009 REFZRA WS R03"

Sequentially clouds and air_temperature are returned as null

```php
    "clouds"                => NULL
    "air_temperature"       => NULL
    "dew_point_temperature" => NULL
    "pressure"              => NULL
```

**Comment by inouire** [comment]
Thanks Johnie for noticing it.
No it is not expected, I'll have a look at it and fix the issue.

**Comment by JohnieWalker** [comment]
The 7d7d4ac76f145c050dfc3788ce2a40c622a87d07 commit deals with the problem. This one can be closed :)
