### ISSUE TITLE
Improved handling of items after a parsing error

### ISSUE THREAD

**Issue by gpdawson** [SagemCassiopee/php-metar-decoder#11]
"KQER 162300Z AUTO 19001KT 8000 /CLR M05/M08 / RMK A02 TSNO"

The above metar code understandably fails on the cloud cover item due to spurious / as well as missing pressure data, but then also fails to recognise the temperature data, even though that element is formatted correctly, and is easily decoded manually by a human reader. 

It would be nice if a failure to find a correctly formatted field didn't prevent later items being correctly parsed e.g. resume processing immediately after the first failed group rather than assuming that failure.

The online parser returns the following data for this metar code. Also I'm not sure why the decoding_exceptions array is empty despite the fact that the invalid format messages are displayed.

Invalid format:
Bad format for clouds information, on chunk "/CLR M05/M08 / RMK A02 TSNO"
Atmospheric pressure not found, on chunk "/CLR M05/M08 / RMK A02 TSNO"

 object(DecodedMetar) 
[
    "raw_metar"             => string(59) "KQER 162300Z AUTO 19001KT 8000 /CLR M05/M08 / RMK A02 TSNO "
    "decoding_exceptions"   => array(0)
    "type"                  => NULL
    "icao"                  => string(4) "KQER"
    "day"                   => int(16)
    "time"                  => string(9) "23:00 UTC"
    "status"                => string(4) "AUTO"
    "surface_wind"          =>  object(SurfaceWind) 
        [
            "SurfaceWind:mean_direction"       =>  object(Value) 
            "SurfaceWind:variable_direction"   => bool(false)
            "SurfaceWind:mean_speed"           =>  object(Value) 
            "SurfaceWind:speed_variations"     => NULL
            "SurfaceWind:direction_variations" => NULL
        ]
    "visibility"            =>  object(Visibility) 
        [
            "Visibility:visibility"        =>  object(Value) 
            "Visibility:minimum"           => NULL
            "Visibility:minimum_direction" => NULL
        ]
    "cavok"                 => bool(false)
    "runways_visual_range"  => NULL
    "present_weather"       => array(0)
    "clouds"                => NULL
    "air_temperature"       => NULL
    "dew_point_temperature" => NULL
    "pressure"              => NULL
    "recent_weather"        => NULL
    "windshear_all_runways" => NULL
    "windshear_runways"     => NULL
]

**Comment by inouire** [comment]
Hello Graham, thanks for the feedback.

First of all the reason why the `decoding_exceptions` array is empty is because it is explicitly flushed for the demonstration website. It is done for security reasons as exceptions can contain sensible information. It's available when you use the library normally.

About your request, I propose to add a mode where one "chunk" is automatically consumed on error. But because there was an error, the "chunk" will only be detected base on whitespace, so it won't be (and can't be) 100% bullet proof, but it will be handy in most cases.

Tell me what you think.

**Comment by gpdawson** [comment]
Your proposal sounds good. On testing I found that for a sample 24hr data there were around 4,500 records that failed parsing and therefore produced no temperature data, but that by post-processing the failed records to find the temperature group using a looser regex expression ('#(M?[0-9]{1,2})/(M?[0-9]{1,2}|[X]{1,2})?#'), that about 3,000 of these failed records did actually contain a readable temperature data chunk. So I would expect your proposed change to give a similar improvement.

**Comment by inouire** [comment]
Hello Graham, you can try the latest version v0.5 (simply run `composer update` in your project) to see if it improves the quality of decoding in case of errors.

Please note that this new behaviour only applies when decoding mode is set to non-strict.

**Comment by gpdawson** [comment]
Well done! At first look this seems to be a big improvement. It may be a week or more until I can do some more extensive tests, to see how many "bad" records now receive valid temperature data, for example. I'll raise a new issue if I do find any new problems.
