### ISSUE TITLE
Metars with missing cloud info

### ISSUE THREAD

**Issue by gpdawson** [SagemCassiopee/php-metar-decoder#13]
PAWI 140753Z AUTO 08034G41KT 1/4SM SN FZFG M18/M21 A2951 RMK PK WND 08041/0752 SLP995 P0000 T11831206 TSNO $ VIA AUTODIAL

This metar generates this exception: Bad format for clouds information, on chunk "M18/M21 A2951 RMK PK WND 08041/0752 SLP995 P0000 T11831206 TSNO $ VIA AUTODIAL"

Also, even in non-strict mode, it then fails to parse temperature information, presumably because parser has already jumped to next chunk after not finding cloud info when expected.

According to the specification here http://weatherfaqs.org.uk/book/export/html/197 the cloud info is "optional", although it also says "When fog or heavy snow is occurring, and it is not possible to determine cloud structure, then these groups are replaced by VVhhh or VV///".

I note that there are typically many metar reports (many thousand daily) which do not contain cloud info, mainly from AUTO stations.

So my question is, should missing cloud info be considered an error by this parser, and is there a better way of dealing with this particular case in order to ensure that temperature data is correctly parsed despite missing cloud info?

**Comment by inouire** [comment]
Hello Graham, thank you for the detailed feedback.
The OACI specification makes it clear that the cloud part is mandatory, so I'll work on a way to make it work, but in non-strict mode only.
What do you think ?

**Comment by gpdawson** [comment]
My own interest is in obtaining as much weather information as possible, so I only use non-strict mode, and would be very happy for non-strict mode to be as forgiving as possible. However I do realise that you can only go so far with how lenient you can be before you increase the chance of extracting incorrect data rather than failing to extract any, so only go as far as you think is reasonable.

**Comment by inouire** [comment]
Hi Graham, I've got some good news !

I've figured out something that gives some pretty good results without being too hazardous on decoding. It is available in v0.7. Be careful that the demo website might not be up-to-date, try it locally instead. 

Can you try it and give me a feedback ?

If you're interested, you can have a look at the principle detailed in the README https://github.com/SagemCassiopee/php-metar-decoder#about-parsing-errors-again

**Comment by jpjoux** [comment]
Dear all, just to inform you, the web site is updated automatically 3 times per day. (~ 8:00,  12:00 & 23:00 Paris time)

**Comment by gpdawson** [comment]
So far the new non-strict parsing is looking very good. Great job.

**Comment by inouire** [comment]
Great, I'll close the issue now. Thank you for helping making this library better.
