### ISSUE TITLE
9999NDV

### ISSUE THREAD

**Issue by filerun** [SagemCassiopee/php-metar-decoder#14]
Seems to choke on 9999NDV

PS Thanks for a great library

**Comment by inouire** [comment]
Hello Vlad, thanks for the feedback. I'll work on the NDV implementation.

Is it ok with you if I add a "NDV" boolean field on the Visibility object ?

**Comment by filerun** [comment]
> Is it ok with you if I add a "NDV" boolean field on the Visibility object ?
That would be great!

P.S. I am working on a little aviation tool which uses the awesome library: http://vmc.today You might find it useful.

**Comment by inouire** [comment]
Hi there, you can try to use the latest release v0.7, it includes the NDV decoding. NDV property is available through the `Visibility->hasNDV()` function.

Be careful that the demo website might not be up-to-date, try it locally instead.

By the way thanks for the link, your tool is very pretty. Is it open source ? What would you say of linking both projects to each other ?

**Comment by jpjoux** [comment]
Dear all, just to inform you, the web site is updated automatically 3 times per day. (~ 8:00,  12:00 & 23:00 Paris time)

**Comment by inouire** [comment]
@filerun any news on this topic ?

**Comment by filerun** [comment]
Sorry for the lack of reply. Got busy on a different project and I barely have time for anything else. It would take a bit of work to make it a public open-source project, but I doubt there are many people interested in it. If you care for seeing some of it's code I could send some over some way. If I get to make an "about" section on the website I will definitely link your library.

**Comment by inouire** [comment]
Thanks, let me know if you have any update. For the moment I'll link your project in the README.
