### ISSUE TITLE
getValue method not found

### ISSUE THREAD

**Issue by bruceyang1998** [SagemCassiopee/php-metar-decoder#15]
Hi, 

I am using this library in an ATIS generator. However, I am not able to use the getValue method with any of the objects. I am still a novice to PHP so could you please have a look at my code and tell me what is wrong here? Thanks. 
```
<?php
require_once 'vendor/autoload.php';

use MetarDecoder\MetarDecoder;

$raw_metar = $_GET["metar"];
$decoder = new MetarDecoder();
$d = $decoder->parse($raw_metar);

print($d->getDewPointTemperature()->getValue());
```

Error message:
`Fatal error: Call to a member function getValue() on null in ...\parser.php`

**Comment by JohnieWalker** [comment]
@bruceyang1998 guess you found out what's the problem? getDewPointTemperature might have returned null if you METAR did not contain it for any reasons...
